//! Async key-value store used to bridge the OIDC second leg.
//!
//! When the RP runs as multiple instances behind a load balancer, the
//! authorization request is generated by instance A but the callback
//! lands on instance B. B needs the `state`, `nonce`, PKCE verifier, and
//! `redirect_uri` A generated. A shared KV store is the standard bridge.

use std::future::Future;
use std::pin::Pin;
use std::time::Duration;

pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

#[derive(Debug, thiserror::Error)]
pub enum KvError {
    #[error("key not found")]
    NotFound,

    #[error("storage backend error: {0}")]
    Storage(String),
}

/// Async key-value store.
///
/// Semantics:
/// - `get` returns `Ok(None)` for missing keys; `Err` is reserved for
///   transport / backend failures.
/// - `put` with `ttl = None` means "no expiration". Callers should always
///   provide a TTL for OIDC pending state.
/// - `delete` is idempotent. Callers MUST delete after consuming a
///   pending entry to prevent replay.
pub trait AsyncKvStore: Send + Sync {
    fn get<'a>(&'a self, key: &'a str) -> BoxFuture<'a, Result<Option<Vec<u8>>, KvError>>;

    fn put<'a>(
        &'a self,
        key: &'a str,
        value: Vec<u8>,
        ttl: Option<Duration>,
    ) -> BoxFuture<'a, Result<(), KvError>>;

    fn delete<'a>(&'a self, key: &'a str) -> BoxFuture<'a, Result<(), KvError>>;
}

// `From<KvError> for OidcError` lives in `error.rs` to keep the conversion
// next to the enum definition (see AGENTS.md "Errors").
